### PR TITLE
Tools version 15.0

### PR DESCRIPTION
**Pull request by Recol**
Required for accessing API's via VS 2017 - https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion?view=vs-2017

### CODE REVIEW

**Comment by rauenzi** [comment]
Can you elaborate on why this is needed?

**Comment by rauenzi** [comment]
Okay so now you just add someone else's plugin??

**Comment by rauenzi** [comment]
Closing this for several reasons:
1. No explanation for changes
2. No response when prompted for explanations
3. The first change involving the toolchain version provides no benefit to this project as we don't access any of those APIs
4. The changes to style.css are not valid css. You can have an html `<link>` element in css.
5. You arbitrarily added a BetterDiscord plugin by someone else to the PR giving no rationale.

**Comment by Recol** [comment]
Apologies for no response, this in particular was directed for compilation, (the prior commits were not intended to be synced with the public repository, merely the API change).

This is due to GitHub automatically syncing commits with open pull requests, the API change was intended for future proofing, but I understand if it's not required.

**Pull request closed without merging**
